# Generated by Django 2.1.2 on 2018-10-08 15:37

from django.db import migrations, models
import django.db.models.deletion
import feeds.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('DOC', 'Documento'), ('IMG', 'Imagen'), ('MPG', 'Video')], max_length=3)),
                ('file', models.FileField(upload_to='./adjuntos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('resumen', models.CharField(max_length=512)),
                ('texto', models.TextField()),
                ('icono', models.ImageField(default='./images/iconos/articulos/no_icono.jpg', upload_to='./images/iconos/articulos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('icono', models.ImageField(default='./iconos/categorias/no_icono.jpg', upload_to='./images/iconos/categorias/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Escritor',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('foto', models.ImageField(default='./images/fotos/no_foto.jpg', upload_to=feeds.models.PathAndRename('./images/fotos/'))),
                ('bibliografia', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Escritor',
                'verbose_name_plural': 'Escritores',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('icono', models.ImageField(default='./iconos/temas/no_icono.jpg', upload_to='./images/iconos/temas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='feeds.Tema'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='feeds.Categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='escritor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='feeds.Escritor'),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='feeds.Articulo'),
        ),
    ]
