# Generated by Django 2.1.2 on 2018-10-09 18:21

from django.db import migrations, models
import django.db.models.deletion
import feeds.models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstiloFicha',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('icono', models.ImageField(null=True, upload_to=feeds.models.PathAndRename('./estilo/icono/'))),
                ('texto_tamanyo', models.CharField(max_length=32, null=True)),
                ('fondo_imagen', models.ImageField(null=True, upload_to=feeds.models.PathAndRename('./estilo/imagen/'))),
                ('fondo_color', models.CharField(max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Estilo-Ficha',
                'verbose_name_plural': 'Estilo-Fichas',
            },
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='icono',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='icono',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='icono',
        ),
        migrations.AddField(
            model_name='articulo',
            name='estilo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='feeds.EstiloFicha'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='estilo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='feeds.EstiloFicha'),
        ),
        migrations.AddField(
            model_name='tema',
            name='estilo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas', to='feeds.EstiloFicha'),
        ),
    ]
